services:
  # PostgreSQL база даних
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_DB: casino
      POSTGRES_USER: patrick
      POSTGRES_PASSWORD: "Getting Started"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patrick -d casino"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Telegram бот
  bot:
    build: .
    container_name: crypto_bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_ID=${ADMIN_ID}
      - DB_DSN=postgresql://patrick:Getting Started@postgres:5432/casino
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data: 